import os
import re
from collections import Counter

ANALYSIS_DIR = "analysis"

def analyze_files():
    """Analyzes slow-unit test case files generated by fuzzing."""
    summary = []
    total_files = 0
    file_sizes = []
    unique_patterns = set()
    
    for filename in os.listdir(ANALYSIS_DIR):
        if filename.startswith("slow-unit-"):
            total_files += 1
            file_path = os.path.join(ANALYSIS_DIR, filename)
            file_size = os.path.getsize(file_path)
            file_sizes.append(file_size)

            with open(file_path, "rb") as f:
                data = f.read()

                # Convert to hex
                hex_data = data.hex()

                # Try decoding as UTF-8 (ignore errors)
                try:
                    decoded_data = data.decode("utf-8")
                except UnicodeDecodeError:
                    decoded_data = "<non-UTF8 data>"

                # Detect repeating patterns in hex
                match = re.search(r"(.+?)\1{3,}", hex_data)  # Look for a sequence that repeats at least 3 times
                if match:
                    pattern_found = match.group(1)
                    unique_patterns.add(pattern_found)
                    pattern_note = f"⚠️ Possible repeating pattern detected: {pattern_found}"
                else:
                    pattern_note = "No obvious repeating patterns."

                # Byte frequency analysis
                byte_counts = Counter(data)
                most_common_byte, most_common_count = byte_counts.most_common(1)[0]
                most_common_byte_hex = hex(most_common_byte)

                # Categorize input characteristics
                if all(b == 0 for b in data):
                    category = "All null bytes"
                elif all(32 <= b <= 126 for b in data):  # ASCII range
                    category = "Mostly printable ASCII"
                elif file_size > 1024:
                    category = "Large binary data"
                else:
                    category = "Uncategorized binary"

                # Store summary
                summary.append(f"| `{filename}` | `{repr(decoded_data)}` | `{hex_data[:20]}...` | `{file_size} bytes` | `{most_common_byte_hex} ({most_common_count} times)` | `{category}` | `{pattern_note}` |")

    # Summary statistics
    min_size = min(file_sizes) if file_sizes else 0
    max_size = max(file_sizes) if file_sizes else 0
    avg_size = sum(file_sizes) / len(file_sizes) if file_sizes else 0

    # Write summary to a report file
    report_path = os.path.join(ANALYSIS_DIR, "report.md")
    with open(report_path, "w") as report:
        report.write("# Fuzzing Input Analysis\n\n")
        report.write(f"**Total Files Analyzed:** `{total_files}`\n\n")
        report.write(f"**Unique Patterns Detected:** `{len(unique_patterns)}`\n\n")
        report.write(f"**File Size Stats:**\n")
        report.write(f"- Smallest File: `{min_size} bytes`\n")
        report.write(f"- Largest File: `{max_size} bytes`\n")
        report.write(f"- Average File Size: `{avg_size:.2f} bytes`\n\n")

        # Table header
        report.write("| File Name | Decoded Data | Hex Representation | Size | Most Common Byte | Category | Pattern Detection |\n")
        report.write("|-----------|-------------|--------------------|------|------------------|----------|-------------------|\n")

        # Add each file's analysis
        report.write("\n".join(summary))
    
    print(f"✅ Analysis completed. Report saved to {report_path}")


if __name__ == "__main__":
    analyze_files()
