import os
from collections import Counter

ANALYSIS_DIR = "analysis"

def extract_ascii(data):
    """Extracts readable ASCII characters from binary data."""
    return "".join(chr(b) if 32 <= b < 127 else "." for b in data)

def analyze_files():
    """Analyzes slow-unit test case files generated by fuzzing."""
    summary = []
    file_sizes = []
    
    for filename in os.listdir(ANALYSIS_DIR):
        if filename.startswith("slow-unit-"):
            file_path = os.path.join(ANALYSIS_DIR, filename)
            
            with open(file_path, "rb") as f:
                data = f.read()

                # File size
                file_size = len(data)
                file_sizes.append(file_size)

                # Hex representation (first 20 bytes for preview)
                hex_data = data.hex()[:40] + ("..." if len(data) > 20 else "")

                # Extract readable ASCII characters
                ascii_data = extract_ascii(data)

                # Count byte occurrences
                byte_counts = Counter(data)
                most_common_byte, most_common_count = byte_counts.most_common(1)[0]

                # Categorize the file
                ascii_ratio = sum(1 for b in data if 32 <= b < 127) / len(data)
                category = "Mostly ASCII" if ascii_ratio > 0.7 else "Binary"

                # Store summary
                summary.append(f"| `{filename}` | `{ascii_data}` | `{hex_data}` | `{file_size} bytes` | `{hex(most_common_byte)} ({most_common_count} times)` | `{category}` |")
    
    # File size stats
    smallest = min(file_sizes)
    largest = max(file_sizes)
    average = sum(file_sizes) / len(file_sizes)
    
    # Write summary to report.md
    report_path = os.path.join(ANALYSIS_DIR, "report.md")
    with open(report_path, "w") as report:
        report.write("# Fuzzing Input Analysis\n\n")
        report.write(f"**Total Files Analyzed:** `{len(file_sizes)}`\n\n")
        report.write(f"**File Size Stats:**\n- Smallest File: `{smallest} bytes`\n")
        report.write(f"- Largest File: `{largest} bytes`\n")
        report.write(f"- Average File Size: `{average:.2f} bytes`\n\n")
        
        # Table header
        report.write("| File Name | ASCII Preview | Hex Representation | Size | Most Common Byte | Category |\n")
        report.write("|-----------|--------------|--------------------|------|------------------|----------|\n")
        report.write("\n".join(summary))
    
    print(f"✅ Analysis completed. Report saved to {report_path}")


if __name__ == "__main__":
    analyze_files()
