import os

ANALYSIS_DIR = "analysis"
REPORT_FILE = os.path.join(ANALYSIS_DIR, "report.md")

def format_hex(hex_data, max_length=50):
    """Truncates long hex data for readability."""
    return hex_data[:max_length] + ("..." if len(hex_data) > max_length else "")

def analyze_files():
    """Analyzes slow-unit test case files generated by fuzzing."""
    summary = []
    file_count = 0
    
    for filename in os.listdir(ANALYSIS_DIR):
        if filename.startswith("slow-unit-"):
            file_path = os.path.join(ANALYSIS_DIR, filename)
            file_count += 1
            
            try:
                with open(file_path, "rb") as f:
                    data = f.read()
                    
                    # Try decoding as UTF-8, else mark as non-UTF8
                    try:
                        decoded_data = data.decode("utf-8")
                    except UnicodeDecodeError:
                        decoded_data = "<non-UTF8 data>"
                    
                    hex_repr = format_hex(data.hex())

                    # Store summary in a table format
                    summary.append(f"| `{filename}` | `{repr(decoded_data)}` | `{hex_repr}` |")
            
            except Exception as e:
                print(f"❌ Error reading {filename}: {e}")

    # Write summary to a Markdown report
    with open(REPORT_FILE, "w") as report:
        report.write("# Fuzzing Input Analysis\n\n")
        report.write(f"**Total Files Analyzed:** `{file_count}`\n\n")
        report.write("| File Name | Decoded Data | Hex Representation |\n")
        report.write("|-----------|-------------|---------------------|\n")
        report.write("\n".join(summary))
    
    print(f"✅ Analysis completed. Report saved to {REPORT_FILE}")


if __name__ == "__main__":
    analyze_files()
